exclude: ^((tests/(.*/)?snapshots/.*)|(.*)/qcreport/template.html)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: "^(conda-recipe)/(.*)$"
      - id: end-of-file-fixer
        exclude: "^(tests/report/assets/(.*))$"
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.6.1"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: "(^cue.mod/)|(^docs/)"
        additional_dependencies:
          - numpy
          - types-requests
          - types-setuptools
          - lxml-stubs
          - types-Pygments
          - types-annoy
          - types-colorama
          - types-psutil
          - types-pywin32

  - repo: local
    hooks:
      - id: copyright-checker
        name: Copyright notice checker
        description: Checks that there is a copyright header in all files
        entry: ./utils/check_copyright.py
        language: python
        pass_filenames: true
        types: [file, python]
        exclude: "^(docs)/(.*)$"
