exclude: ^(tests/snapshots/.*)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: "^(conda-recipe)/(.*)$"
      - id: end-of-file-fixer
        exclude: "^(.*)/webreport/template.html$"
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.2.1"
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies:
          - pydoclint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: "(^cue.mod/)|(^docs/)"
        additional_dependencies:
          - numpy
          - types-requests
          - types-setuptools
          - lxml-stubs
          - types-Pygments
          - types-annoy
          - types-colorama
          - types-psutil
          - types-pywin32

  - repo: local
    hooks:
      - id: copyright-checker
        name: Copyright notice checker
        description: Checks that there is a copyright header in all files
        entry: ./utils/check_copyright.py
        language: python
        pass_filenames: true
        types: [file, python]
        exclude: "^(docs)/(.*)$"
