{% set version = "0.0.0" %}

package:
  name: pixelgen-pixelator
  version: {{ version }}

source:
  path: ../../dist/pixelator-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: |
    python -m pip install --no-deps --ignore-installed pixelator-{{ version }}.tar.gz

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python>=3.8,<3.11
    - python-annoy<=1.17.0
    - anndata
    - appdirs
    - beautifulsoup4
    - certifi
    - charset-normalizer
    - click
    - colorama
    - cutadapt>=3.5
    - cycler
    - dnaio
    - esda
    - fonttools
    - future
    - idna
    - python-igraph>=0.10
    - python-isal
    - jinja2
    - joblib
    - kiwisolver
    - leidenalg
    - libpysal
    - lxml
    - markupsafe
    - matplotlib<3.6
    - numpy
    - onnxruntime
    - packaging
    - pandas>=2.0.0
    - pillow
    - plotly
    - pybktree
    - pyfastx
    - pyparsing
    - python-dateutil
    - python-kaleido
    - pytz
    - pyyaml
    - regex
    - requests
    - scanpy
    - scikit-learn
    - scipy
    - seaborn
    - setuptools-scm
    - six
    - soupsieve
    - tenacity
    - texttable
    - threadpoolctl
    - tomli
    - umi_tools
    - urllib3
    - xopen
    - yapf
    - yappi
    - fastp
    - poetry-dynamic-versioning
    - pyarrow
    - semver

about:
  license: GPL v2
  license_family: GPL
  summary: "Pixelator is a software package to process sequencing FASTQ from Molecular Pixelation (MPX) assays and analyze PXL data (maintained by Pixelgen Technologies AB)"
