name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  # TODO lock versions?
  - python=3.11
  - mamba
  - python-annoy
  - tox
  - poetry
  - poetry-plugin-export
  - poetry-dynamic-versioning[plugin]
  - virtualenv
  - fastp
  - go-task
  - pyyaml
