name: "setup-image-build-env"
description: "Install and setup Docker and authenticate with the Pixelgen container registries"
inputs:
  aws-role-to-assume:
    description: "The AWS IAM role to assume to get access to the AWS ECR registry"
    default: "arn:aws:iam::890888997283:role/GithubActionsRole"
  aws-role-session-name:
    description: "The name of the AWS IAM role session"
    default: "GitHubActions"
  aws-registry:
    description: "The AWS ECR registry to authenticate with"
    default: "890888997283.dkr.ecr.eu-north-1.amazonaws.com"
  quay-username:
    description: "The username for Quay Container Registry"
    required: true
  quay-password:
    description: "The password for Quay Container Registry"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-north-1
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-session-name }}

    - name: Login to AWS ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.aws-registry }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Login to Quay Container Registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-password }}
