"""Functions for computing node-level Partial Least Squares (PLS) regression.

Copyright © 2025 Pixelgen Technologies AB.
"""

from __future__ import annotations

import logging
from typing import List, Literal, Optional, Union

import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn.cross_decomposition import PLSRegression

from pixelator.common.graph import Graph
from pixelator.common.graph.backends.implementations._networkx import _mat_pow

logger = logging.getLogger(__name__)


def _residualize_matrix(X: np.ndarray, model_mat: np.ndarray) -> np.ndarray:
    """Residualize matrix X against model_mat using OLS.

    :param X: Matrix to residualize (n_samples, n_features)
    :param model_mat: Covariates matrix (n_samples, n_covariates)
    :return: Residualized matrix
    """
    # Solve M @ B = X for B
    B, _, _, _ = np.linalg.lstsq(model_mat, X, rcond=None)
    return X - model_mat @ B


def _create_node_neighborhood_abundance_matrix(
    cg: Graph,
    k: int = 2,
    use_weights: bool = False,
    min_weight: float = 0.0,
    normalization: Literal["L1", "CLR", "LogNormalize", "none"] = "L1",
    scale: bool = True,
    model_mat: Optional[np.ndarray] = None,
) -> pd.DataFrame:
    """Create a node neighborhood abundance matrix.

    This function creates a node abundance matrix for a Graph object. The node
    abundance matrix is generated by expanding the counts matrix of the Graph to
    include neighborhood counts up to `k` steps away, using the adjacency matrix of
    the cell graph. The resulting matrix can be normalized using various methods,
    such as L1 normalization, centered log-ratio transformation, or log
    normalization. The columns of the resulting matrix can also be scaled to have
    mean 0 and standard deviation 1. This function is used internally for creating
    the predictor matrix X in the `node_pls` function and for other internal
    analyses that require a neighborhood-expanded and normalized node abundance matrix.

    Args:
        cg: A Graph object for which to create the node abundance matrix.
        k: An integer value specifying the maximum steps from each node to
            expand the neighborhood for creating the predictor matrix X. If `k > 0`,
            the counts will be expanded to include neighborhood counts up to `k`
            steps away using the adjacency matrix of the Graph. Defaults to 2.
        use_weights: Logical indicating whether to use edge weights when
            expanding the adjacency matrix for creating the predictor matrix X.
            Defaults to False.
        min_weight: A numeric value specifying the minimum edge weight to
            consider when expanding the adjacency matrix for creating the predictor
            matrix X. Edges with weights below this threshold will be ignored.
            Defaults to 0.
        normalization: A character value specifying the normalization method
            to apply to the predictor matrix X before fitting the PLS model.
            Options are "L1" for L1 normalization (scaling rows to sum to 1),
            "CLR" for centered log-ratio transformation, "LogNormalize" for log
            normalization, and "none" for no normalization. Defaults to "L1".
        scale: Logical indicating whether to scale the predictor matrix X
            by centering and scaling the columns to have mean 0 and standard
            deviation 1. Defaults to True.
        model_mat: An optional numeric matrix of covariates to residualize
            out of the predictor matrix X. The number of rows in `model_mat` must
            match the number of nodes in the Graph. If provided, the function will
            residualize the predictor matrix X by regressing out the effects of the
            covariates in `model_mat` before returning the final matrix.
            Defaults to None.

    Returns:
        pd.DataFrame: A DataFrame containing expanded and normalized node
            abundance values.

    Raises:
        ValueError: If the number of rows in model_mat does not match the
            number of nodes in the graph.

    """
    counts = cg.node_marker_counts
    X = counts.values.astype(np.float64)

    if k > 0:
        A = cg.get_adjacency_sparse(node_ordering=counts.index)
        # Add self-loops to represent "at most k steps"
        A = A + sp.eye(A.shape[0], format="csr")

        if use_weights:
            # Divide by row sum to get the stochastic matrix
            D = sp.diags_array(1 / A.sum(axis=1), format="csr")
            A = (D @ A).T

        if k > 1:
            # Expand to k-step neighborhood
            W = _mat_pow(A, k, prune_threshold=min_weight if min_weight > 0 else None)

            if not use_weights:
                # Set all non-zero entries to 1 to get unweighted neighborhood counts
                W.data = np.ones_like(W.data)

        else:
            W = A

        # Neighborhood abundance is W @ X
        X = (W @ X).astype(np.float64)

    # Transform/Normalize X
    if normalization == "CLR":
        X = np.log1p(X)
        X = X - np.mean(X, axis=1, keepdims=True)
    elif normalization == "L1":
        row_sums = np.sum(X, axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        X = X / row_sums
    elif normalization == "LogNormalize":
        row_sums = np.sum(X, axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        X = (X / row_sums) * 1e4
        X = np.log1p(X)

    # Residualize X
    if model_mat is not None:
        if model_mat.shape[0] != X.shape[0]:
            raise ValueError(
                f"Number of rows in model_mat ({model_mat.shape[0]}) must match "
                f"number of nodes in graph ({X.shape[0]})."
            )
        X = _residualize_matrix(X, model_mat)

    # Z-score scale columns
    if scale:
        std = np.std(X, axis=0)
        std[std == 0] = 1
        X = (X - np.mean(X, axis=0)) / std

    return pd.DataFrame(X, index=counts.index, columns=counts.columns)


def node_pls(
    cg: Graph,
    y_vars: Union[str, List[str]],
    x_vars: Optional[List[str]] = None,
    k: int = 2,
    use_weights: bool = False,
    min_weight: float = 0.0,
    ncomp: int = 1,
    normalization: Literal["L1", "CLR", "LogNormalize", "none"] = "L1",
    scale: bool = True,
    model_mat: Optional[np.ndarray] = None,
) -> PLSRegression:
    """Perform Partial Least Squares (PLS) regression on a Graph object.

    This function creates a predictor matrix X based on the counts matrix of the Graph,
    optionally expanding it to include neighborhood counts up to `k` steps away.
    The response matrix Y is created based on the specified `y_vars`, which can be
    either columns from the normalized counts matrix X or node variables from the
    graph data. The function then fits a PLS model using the `sklearn` package and
    returns the fitted model object.

    Args:
        cg: A Graph object.
        y_vars: A string or list of variable names to use as responses (Y).
            These can be column names from the counts matrix or node variables from
            the graph data. The function will check for the presence of these
            variables and fetch them accordingly. If any of the specified `y_vars`
            are found in the counts matrix, they will be taken from the normalized
            counts matrix X. These variables will only be used as response variables
            and removed from the predictor matrix X to avoid data leakage. However,
            they will have been normalized and/or neighborhood-expanded as part of X
            before being subset out for Y.
        x_vars: A list of variable names to use as predictors (X). These
            should be column names from the counts matrix of the Graph. If None,
            all columns from the counts matrix will be used as predictors.
            Defaults to None.
        k: An integer value specifying the maximum steps from each node to
            expand the neighborhood for creating the predictor matrix X. If `k > 0`,
            the counts will be expanded to include neighborhood counts up to `k`
            steps away using the adjacency matrix of the Graph. Defaults to 2.
        use_weights: Logical indicating whether to use edge weights when
            expanding the adjacency matrix for creating the predictor matrix X.
            Defaults to False.
        min_weight: A numeric value specifying the minimum edge weight to
            consider when expanding the adjacency matrix for creating the predictor
            matrix X. Edges with weights below this threshold will be ignored.
            Defaults to 0.
        ncomp: An integer value specifying the number of PLS components
            to compute. Defaults to 1.
        normalization: A character value specifying the normalization method
            to apply to the predictor matrix X before fitting the PLS model.
            Options are "L1" for L1 normalization (scaling rows to sum to 1),
            "CLR" for centered log-ratio transformation, "LogNormalize" for log
            normalization, and "none" for no normalization. Defaults to "L1".
        scale: Logical indicating whether to scale the predictor matrix X
            by centering and scaling the columns to have mean 0 and standard
            deviation 1. Defaults to True.
        model_mat: An optional numeric matrix of covariates to residualize
            out of the predictor matrix X. The number of rows in `model_mat` must
            match the number of nodes in the Graph. If provided, the function will
            residualize the predictor matrix X by regressing out the effects of the
            covariates in `model_mat` before fitting the PLS model.
            Defaults to None.

    Returns:
        PLSRegression: A fitted sklearn PLSRegression model, which contains the
            results of the PLS regression including coefficients, scores,
            and loadings.

    Raises:
        ValueError: If variables are not found or if the input matrices are
            incompatible.

    """
    if isinstance(y_vars, str):
        y_vars = [y_vars]

    # Create expanded and normalized matrix
    X_expanded = _create_node_neighborhood_abundance_matrix(
        cg=cg,
        k=k,
        use_weights=use_weights,
        min_weight=min_weight,
        normalization=normalization,
        scale=scale,
        model_mat=model_mat,
    )

    counts = cg.node_marker_counts
    y_in_counts = [y for y in y_vars if y in counts.columns]
    y_not_in_counts = [y for y in y_vars if y not in counts.columns]

    # Extract Y from expanded matrix if present in counts
    Y_data = {}
    if y_in_counts:
        for y in y_in_counts:
            Y_data[y] = X_expanded[y].values
        # Drop response variables from X to avoid data leakage
        X_expanded = X_expanded.drop(columns=y_in_counts)

    # Extract Y from graph attributes if not in counts
    if y_not_in_counts:
        v_attr_dict = {v.index: v.data for v in cg.vs}
        for y in y_not_in_counts:
            # Reindex to match counts.index
            y_col = []
            for node_id in counts.index:
                node_data = v_attr_dict.get(node_id)
                if node_data is None or y not in node_data:
                    raise ValueError(
                        f"Variable '{y}' not found in counts or graph attributes for node {node_id}."
                    )
                y_col.append(node_data[y])
            Y_data[y] = y_col

    if not Y_data:
        raise ValueError("No valid response variables found in 'y_vars'.")

    # Combine Y_data into a matrix
    Y = pd.DataFrame(Y_data).reindex(columns=y_vars).values

    # Subset X if specified
    if x_vars is not None:
        missing_x = [x for x in x_vars if x not in X_expanded.columns]
        if missing_x:
            raise ValueError(
                f"The following x_vars are not found: {', '.join(missing_x)}"
            )
        X = X_expanded[x_vars].values
    else:
        X = X_expanded.values

    # Fit PLS model
    pls_model = PLSRegression(n_components=ncomp, scale=False)
    pls_model.fit(X, Y)

    return pls_model
