"""Functions for computing node-level Partial Least Squares (PLS) regression.

Copyright © 2025 Pixelgen Technologies AB.
"""

from __future__ import annotations

import logging
from typing import List, Literal, Optional, Union

import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn.cross_decomposition import PLSRegression

from pixelator.common.graph import Graph
from pixelator.common.graph.backends.implementations._networkx import _mat_pow

logger = logging.getLogger(__name__)


def _residualize_matrix(X: np.ndarray, model_mat: np.ndarray) -> np.ndarray:
    """Residualize matrix X against model_mat using OLS.

    :param X: Matrix to residualize (n_samples, n_features)
    :param model_mat: Covariates matrix (n_samples, n_covariates)
    :return: Residualized matrix
    """
    # Solve M @ B = X for B
    B, _, _, _ = np.linalg.lstsq(model_mat, X, rcond=None)
    return X - model_mat @ B


def _create_node_neighborhood_abundance_matrix(
    cg: Graph,
    k: int = 2,
    use_weights: bool = False,
    min_weight: float = 0.0,
    normalization: Literal["L1", "CLR", "LogNormalize", "none"] = "L1",
    scale: bool = True,
    model_mat: Optional[np.ndarray] = None,
) -> pd.DataFrame:
    """Create a node abundance matrix for a Graph object.

    The node abundance matrix is generated by expanding the counts matrix of the Graph
    to include neighborhood counts up to `k` steps away.

    :param cg: A Graph object.
    :param k: Maximum steps from each node to expand the neighborhood. Default is 2.
    :param use_weights: Whether to use edge weights when expanding. Default is False.
    :param min_weight: Minimum edge weight to consider when expanding. Default is 0.
    :param normalization: Normalization method to apply. Options are "L1", "CLR",
        "LogNormalize", and "none". Default is "L1".
    :param scale: Whether to center and scale columns to have mean 0 and std 1.
        Default is True.
    :param model_mat: Optional numeric matrix of covariates to residualize out.
        Default is None.
    :return: A DataFrame containing expanded and normalized node abundance values.
    """
    counts = cg.node_marker_counts
    X = counts.values.astype(np.float64)

    if k > 0:
        A = cg.get_adjacency_sparse(node_ordering=counts.index)
        # Add self-loops to represent "at most k steps"
        A = A + sp.eye(A.shape[0], format="csr")

        if not use_weights:
            # Set all positive weights to 1
            A.data = np.ones_like(A.data)

        # Apply min_weight threshold
        if min_weight > 0:
            A.data[A.data < min_weight] = 0
            A.eliminate_zeros()

        if k > 1:
            # Expand to k-step neighborhood
            W = _mat_pow(A, k, prune_threshold=min_weight if min_weight > 0 else None)
        else:
            W = A

        # Set all positive weights in the expanded matrix to 1 if not using weights
        if not use_weights:
            W.data = np.ones_like(W.data)

        # Neighborhood abundance is W @ X
        X = (W @ X).astype(np.float64)

    # Transform/Normalize X
    if normalization == "CLR":
        X = np.log1p(X)
        X = X - np.mean(X, axis=1, keepdims=True)
    elif normalization == "L1":
        row_sums = np.sum(X, axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        X = X / row_sums
    elif normalization == "LogNormalize":
        row_sums = np.sum(X, axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        X = (X / row_sums) * 1e4
        X = np.log1p(X)

    # Residualize X
    if model_mat is not None:
        if model_mat.shape[0] != X.shape[0]:
            raise ValueError(
                f"Number of rows in model_mat ({model_mat.shape[0]}) must match "
                f"number of nodes in graph ({X.shape[0]})."
            )
        X = _residualize_matrix(X, model_mat)

    # Z-score scale columns
    if scale:
        std = np.std(X, axis=0)
        std[std == 0] = 1
        X = (X - np.mean(X, axis=0)) / std

    return pd.DataFrame(X, index=counts.index, columns=counts.columns)


def node_pls(
    cg: Graph,
    y_vars: Union[str, List[str]],
    x_vars: Optional[List[str]] = None,
    k: int = 2,
    use_weights: bool = False,
    min_weight: float = 0.0,
    ncomp: int = 1,
    normalization: Literal["L1", "CLR", "LogNormalize", "none"] = "L1",
    scale: bool = True,
    model_mat: Optional[np.ndarray] = None,
) -> PLSRegression:
    """Perform Partial Least Squares (PLS) regression on a Graph object.

    This function creates a predictor matrix X based on the counts matrix of the Graph,
    optionally expanding it to include neighborhood counts up to `k` steps away.
    The response matrix Y is created based on the specified `y_vars`, which can be
    either columns from the expanded counts matrix X or node variables from the graph.

    :param cg: A Graph object.
    :param y_vars: Variable name(s) to use as responses (Y).
    :param x_vars: Variable names to use as predictors (X). If None, all columns
        from the counts matrix (minus y_vars) will be used. Default is None.
    :param k: Steps to expand neighborhood for predicting matrix X. Default is 2.
    :param use_weights: Whether to use edge weights when expanding. Default is False.
    :param min_weight: Minimum edge weight to consider when expanding. Default is 0.
    :param ncomp: Number of PLS components to compute. Default is 1.
    :param normalization: Normalization method to apply. Options are "L1", "CLR",
        "LogNormalize", and "none". Default is "L1".
    :param scale: Whether to center and scale columns. Default is True.
    :param model_mat: Optional numeric matrix of covariates to residualize out.
        Default is None.
    :return: A fitted sklearn PLSRegression model.
    """
    if isinstance(y_vars, str):
        y_vars = [y_vars]

    # Create expanded and normalized matrix
    X_expanded = _create_node_neighborhood_abundance_matrix(
        cg=cg,
        k=k,
        use_weights=use_weights,
        min_weight=min_weight,
        normalization=normalization,
        scale=scale,
        model_mat=model_mat,
    )

    counts = cg.node_marker_counts
    y_in_counts = [y for y in y_vars if y in counts.columns]
    y_not_in_counts = [y for y in y_vars if y not in counts.columns]

    # Extract Y from expanded matrix if present in counts
    Y_data = {}
    if y_in_counts:
        for y in y_in_counts:
            Y_data[y] = X_expanded[y].values
        # Drop response variables from X to avoid data leakage
        X_expanded = X_expanded.drop(columns=y_in_counts)

    # Extract Y from graph attributes if not in counts
    if y_not_in_counts:
        v_attr_dict = {v.index: v.data for v in cg.vs}
        for y in y_not_in_counts:
            # Reindex to match counts.index
            y_col = []
            for node_id in counts.index:
                node_data = v_attr_dict.get(node_id)
                if node_data is None or y not in node_data:
                    raise ValueError(
                        f"Variable '{y}' not found in counts or graph attributes for node {node_id}."
                    )
                y_col.append(node_data[y])
            Y_data[y] = y_col

    if not Y_data:
        raise ValueError("No valid response variables found in 'y_vars'.")

    # Combine Y_data into a matrix
    Y = pd.DataFrame(Y_data).reindex(columns=y_vars).values

    # Subset X if specified
    if x_vars is not None:
        missing_x = [x for x in x_vars if x not in X_expanded.columns]
        if missing_x:
            raise ValueError(
                f"The following x_vars are not found: {', '.join(missing_x)}"
            )
        X = X_expanded[x_vars].values
    else:
        X = X_expanded.values

    # Fit PLS model
    pls_model = PLSRegression(n_components=ncomp, scale=False)
    pls_model.fit(X, Y)

    return pls_model
