name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_SIGNATURES_REPO_TOKEN }}
        with:
          path-to-signatures: 'signatures/pixelator/version1/cla.json'
          path-to-document: 'https://software.pixelgen.com/assets/files/Pixelgen_Individual_Contributor_License_Agreement_(CLA)-671dac61b4e5458371c420b857122e5a.pdf' # e.g. a CLA or a DCO document
          branch: 'main'
          allowlist: johandahlberg,fbdtemme,ptajvar,maxkarlsson,ludvigla,vincent-van-hoef,dependabot[bot]
          remote-organization-name: PixelgenTechnologies
          remote-repository-name: cla-signatures
